name: Test Steam Deploy

on: workflow_dispatch

jobs:
  testSteamDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p build/StandaloneWindows
          mkdir -p build/StandaloneLinux64
          mkdir -p build/StandaloneWindows64
          mkdir -p build/StandaloneOSX
          touch build/StandaloneWindows/test.txt
          touch build/StandaloneLinux64/test.txt
          touch build/StandaloneWindows64/test.txt
          touch build/StandaloneOSX/test.txt
          chmod -R 777 build
      - id: setup-steam
        uses: CyberAndrii/setup-steamcmd@master
      - env:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
          ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
          ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
          appId: 1742850
          buildDescription: v0.0.1
          rootPath: build
          depot1Path: StandaloneWindows
          depot2Path: StandaloneLinux64
          depot3Path: StandaloneWindows64
          depot4Path: StandaloneOSX
          releaseBranch: prerelease
        run: |
          export STEAM_HOME=${{ steps.setup-steam.outputs.directory }}
          export STEAM_CMD=${{ steps.setup-steam.outputs.executable }}
          chmod +x ./steam_deploy.sh
          ./steam_deploy.sh
