name: Test Steam Deploy

on: workflow_dispatch

jobs:
  testSteamDeploy:
    runs-on: ubuntu-latest
    env:
      username: ${{ secrets.STEAM_USERNAME }}
      password: ${{ secrets.STEAM_PASSWORD }}
      mfaCode: ${{ secrets.STEAM_MFA_CODE }}
      personalAccessToken: ${{ secrets.CGS_PAT }}
      configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
      ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
      ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
      appId: 1742850
      buildDescription: v0.0.1
      rootPath: build
      depot1Path: StandaloneWindows
      depot2Path: StandaloneLinux64
      depot3Path: StandaloneWindows64
      depot4Path: StandaloneOSX
      releaseBranch: prerelease
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p build/StandaloneWindows
          mkdir -p build/StandaloneLinux64
          mkdir -p build/StandaloneWindows64
          mkdir -p build/StandaloneOSX
          touch build/StandaloneWindows/test.txt
          touch build/StandaloneLinux64/test.txt
          touch build/StandaloneWindows64/test.txt
          touch build/StandaloneOSX/test.txt
          chmod -R 777 build
      - id: steamsetup
        uses: CyberAndrii/setup-steamcmd@v1.1.1
      - id: deploy
        shell: bash
        run: |
          export STEAM_HOME=${{ steps.steamsetup.outputs.directory }}
          export STEAM_CMD=${{ steps.steamsetup.outputs.executable }}
          chmod +x ./steam_deploy.sh
          ./steam_deploy.sh
          echo "Exporting STEAM_CONFIG_VDF..."
          export STEAM_CONFIG_VDF="$(cat $STEAM_HOME/config/config.vdf)"
          echo "::set-output name=STEAM_CONFIG_VDF::$STEAM_CONFIG_VDF"
          echo "Exporting STEAM_SSFN_FILE_NAME..."
          export STEAM_SSFN_FILE_NAME="$(basename $(ls $STEAM_HOME/ssfn*))"
          echo "::set-output name=STEAM_SSFN_FILE_NAME::$STEAM_SSFN_FILE_NAME"
          echo "Exporting STEAM_SSFN_FILE_CONTENTS..."
          export STEAM_SSFN_FILE_CONTENTS="$(cat $STEAM_HOME/$STEAM_SSFN_FILE_NAME | base64)"
          echo "::set-output name=STEAM_SSFN_FILE_CONTENTS::$STEAM_SSFN_FILE_CONTENTS"
          echo "Exported secrets!"
      - uses: gliech/create-github-secret-action@v1
        with:
          name: STEAM_CONFIG_VDF
          value: ${{ steps.deploy.outputs.STEAM_CONFIG_VDF }}
          pa_token: ${{ inputs.personalAccessToken }}
      - uses: gliech/create-github-secret-action@v1
        with:
          name: STEAM_SSFN_FILE_NAME
          value: ${{ steps.deploy.outputs.STEAM_SSFN_FILE_NAME }}
          pa_token: ${{ inputs.personalAccessToken }}
      - uses: gliech/create-github-secret-action@v1
        with:
          name: STEAM_SSFN_FILE_CONTENTS
          value: ${{ steps.deploy.outputs.STEAM_SSFN_FILE_CONTENTS }}
          pa_token: ${{ inputs.personalAccessToken }}
